env:
  - GHCVER=7.10.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo add-apt-repository -y ppa:openstack-ubuntu-testing/icehouse
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER libleveldb-dev libsnappy-dev
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH

install:
  - cabal update
  - cabal install -j --only-dependencies --enable-tests --enable-documentation
  - cabal configure -v2
  - cabal build -v2

script: cabal test
